### ISSUE TITLE
Cannot find module './dist/index.js'

### ISSUE THREAD

**Issue by adamwan92** [studiointeract/accounts-ui#105]
Getting this error consistently on Meteor 1.4+

> W20170315-03:11:06.754(8)? (STDERR) /Users/adamwan/.meteor/packages/meteor-tool/.1.4.3_2.moutdk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
> W20170315-03:11:06.759(8)? (STDERR) 						throw(ex);
> W20170315-03:11:06.759(8)? (STDERR) 						^
> W20170315-03:11:06.760(8)? (STDERR)
> W20170315-03:11:06.760(8)? (STDERR) Error: Cannot find module './dist/index.js'
> W20170315-03:11:06.760(8)? (STDERR)     at require (packages/modules-runtime.js:123:19)
> W20170315-03:11:06.761(8)? (STDERR)     at meteorInstall.node_modules.tracker-component.index.js (packages/modules.js:31825:18)
> W20170315-03:11:06.761(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
> W20170315-03:11:06.761(8)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
> W20170315-03:11:06.762(8)? (STDERR)     at Module.Mp.import (/Users/adamwan/.meteor/packages/modules/.0.7.9.1aboc6k++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
> W20170315-03:11:06.762(8)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.imports.ui.components.LoginForm.jsx (packages/std:accounts-ui/imports/ui/components/LoginForm.jsx:1:215)
> W20170315-03:11:06.762(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
> W20170315-03:11:06.762(8)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
> W20170315-03:11:06.763(8)? (STDERR)     at Module.Mp.import (/Users/adamwan/.meteor/packages/modules/.0.7.9.1aboc6k++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
> W20170315-03:11:06.763(8)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.main_server.js (packages/std:accounts-ui/main_server.js:1:556)

**Comment by adamwan92** [comment]
For people looking for a solution:
So I ended up importing this whole package locally. Had to do some adjustments to make it work, but most importantly I had to remove the tracker-component import.

I'm using ultimatejs TrackerReact instead.

**Comment by Elviron** [comment]
Closing due to inactivity @adamwan92  
Open new issue if it still persists.
