### ISSUE TITLE
App crashes after adding accounts-ui (forget to call 'Npm.depends')

### ISSUE THREAD

**Issue by FBosler** [studiointeract/accounts-ui#114]
Hi everybody,

tried adding accounts. Didn't really work, now the app crashes, for exact error log see below. Just to be sure I did remove autopublish, got the same error. Any idea whats going on here?
Cheers

```
I20170425-07:14:00.726(-4)? ** You've set up some data subscriptions with Meteor.publish(), but
I20170425-07:14:00.765(-4)? ** you still have autopublish turned on. Because autopublish is still
I20170425-07:14:00.766(-4)? ** on, your Meteor.publish() calls won't have much effect. All data
I20170425-07:14:00.766(-4)? ** will still be sent to all clients.
I20170425-07:14:00.766(-4)? **
I20170425-07:14:00.766(-4)? ** Turn off autopublish by removing the autopublish package:
I20170425-07:14:00.766(-4)? **
I20170425-07:14:00.767(-4)? **   $ meteor remove autopublish
I20170425-07:14:00.767(-4)? **
I20170425-07:14:00.767(-4)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20170425-07:14:00.767(-4)? ** for each collection that you want clients to see.
I20170425-07:14:00.767(-4)?
W20170425-07:14:00.849(-4)? (STDERR) /Users/FBosler/.meteor/packages/meteor-tool/.1.4.4_1.1ygrsyx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170425-07:14:00.850(-4)? (STDERR) 						throw(ex);
W20170425-07:14:00.850(-4)? (STDERR) 						^
W20170425-07:14:00.850(-4)? (STDERR)
W20170425-07:14:00.850(-4)? (STDERR) Error: Can't find npm module 'tracker-component'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170425-07:14:00.850(-4)? (STDERR)     at Object.require (/Users/FBosler/Desktop/webDev/reclist/reclist/.meteor/local/build/programs/server/boot.js:200:17)
W20170425-07:14:00.850(-4)? (STDERR)     at options.fallback (packages/modules-runtime.js:479:18)
W20170425-07:14:00.851(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:126:16)
W20170425-07:14:00.851(-4)? (STDERR)     at Module.Mp.importSync (/Users/FBosler/.meteor/packages/modules/.0.8.2.1mjg3y1++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:82:24)
W20170425-07:14:00.851(-4)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.imports.ui.components.LoginForm.jsx (packages/std:accounts-ui/imports/ui/components/LoginForm.jsx:1:211)
W20170425-07:14:00.851(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170425-07:14:00.852(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170425-07:14:00.852(-4)? (STDERR)     at Module.Mp.importSync (/Users/FBosler/.meteor/packages/modules/.0.8.2.1mjg3y1++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:82:24)
W20170425-07:14:00.852(-4)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.main_server.js (packages/std:accounts-ui/main_server.js:1:536)
W20170425-07:14:00.852(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
=> Exited with code: 1
I20170425-07:14:02.454(-4)? ** You've set up some data subscriptions with Meteor.publish(), but
I20170425-07:14:02.454(-4)? ** you still have autopublish turned on. Because autopublish is still
I20170425-07:14:02.455(-4)? ** on, your Meteor.publish() calls won't have much effect. All data
I20170425-07:14:02.455(-4)? ** will still be sent to all clients.
I20170425-07:14:02.455(-4)? **
I20170425-07:14:02.455(-4)? ** Turn off autopublish by removing the autopublish package:
I20170425-07:14:02.455(-4)? **
I20170425-07:14:02.455(-4)? **   $ meteor remove autopublish
I20170425-07:14:02.455(-4)? **
I20170425-07:14:02.455(-4)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20170425-07:14:02.456(-4)? ** for each collection that you want clients to see.
I20170425-07:14:02.456(-4)?
W20170425-07:14:02.608(-4)? (STDERR) /Users/FBosler/.meteor/packages/meteor-tool/.1.4.4_1.1ygrsyx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170425-07:14:02.609(-4)? (STDERR) 						throw(ex);
W20170425-07:14:02.609(-4)? (STDERR) 						^
W20170425-07:14:02.609(-4)? (STDERR)
W20170425-07:14:02.609(-4)? (STDERR) Error: Can't find npm module 'tracker-component'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170425-07:14:02.610(-4)? (STDERR)     at Object.require (/Users/FBosler/Desktop/webDev/reclist/reclist/.meteor/local/build/programs/server/boot.js:200:17)
W20170425-07:14:02.610(-4)? (STDERR)     at options.fallback (packages/modules-runtime.js:479:18)
W20170425-07:14:02.610(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:126:16)
W20170425-07:14:02.611(-4)? (STDERR)     at Module.Mp.importSync (/Users/FBosler/.meteor/packages/modules/.0.8.2.1mjg3y1++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:82:24)
W20170425-07:14:02.611(-4)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.imports.ui.components.LoginForm.jsx (packages/std:accounts-ui/imports/ui/components/LoginForm.jsx:1:211)
W20170425-07:14:02.611(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170425-07:14:02.611(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170425-07:14:02.611(-4)? (STDERR)     at Module.Mp.importSync (/Users/FBosler/.meteor/packages/modules/.0.8.2.1mjg3y1++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:82:24)
W20170425-07:14:02.611(-4)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.main_server.js (packages/std:accounts-ui/main_server.js:1:536)
W20170425-07:14:02.611(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
=> Exited with code: 1
I20170425-07:14:04.285(-4)? ** You've set up some data subscriptions with Meteor.publish(), but
I20170425-07:14:04.285(-4)? ** you still have autopublish turned on. Because autopublish is still
I20170425-07:14:04.285(-4)? ** on, your Meteor.publish() calls won't have much effect. All data
I20170425-07:14:04.286(-4)? ** will still be sent to all clients.
I20170425-07:14:04.286(-4)? **
I20170425-07:14:04.286(-4)? ** Turn off autopublish by removing the autopublish package:
I20170425-07:14:04.286(-4)? **
I20170425-07:14:04.287(-4)? **   $ meteor remove autopublish
I20170425-07:14:04.287(-4)? **
I20170425-07:14:04.287(-4)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20170425-07:14:04.287(-4)? ** for each collection that you want clients to see.
I20170425-07:14:04.288(-4)?
W20170425-07:14:04.426(-4)? (STDERR) /Users/FBosler/.meteor/packages/meteor-tool/.1.4.4_1.1ygrsyx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170425-07:14:04.426(-4)? (STDERR) 						throw(ex);
W20170425-07:14:04.426(-4)? (STDERR) 						^
W20170425-07:14:04.426(-4)? (STDERR)
W20170425-07:14:04.427(-4)? (STDERR) Error: Can't find npm module 'tracker-component'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170425-07:14:04.427(-4)? (STDERR)     at Object.require (/Users/FBosler/Desktop/webDev/reclist/reclist/.meteor/local/build/programs/server/boot.js:200:17)
W20170425-07:14:04.427(-4)? (STDERR)     at options.fallback (packages/modules-runtime.js:479:18)
W20170425-07:14:04.427(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:126:16)
W20170425-07:14:04.427(-4)? (STDERR)     at Module.Mp.importSync (/Users/FBosler/.meteor/packages/modules/.0.8.2.1mjg3y1++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:82:24)
W20170425-07:14:04.427(-4)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.imports.ui.components.LoginForm.jsx (packages/std:accounts-ui/imports/ui/components/LoginForm.jsx:1:211)
W20170425-07:14:04.427(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170425-07:14:04.428(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170425-07:14:04.428(-4)? (STDERR)     at Module.Mp.importSync (/Users/FBosler/.meteor/packages/modules/.0.8.2.1mjg3y1++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:82:24)
W20170425-07:14:04.428(-4)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.main_server.js (packages/std:accounts-ui/main_server.js:1:536)
W20170425-07:14:04.428(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)

```

My installed npm packages
```
├── babel-runtime@6.23.0
├── meteor-node-stubs@0.2.6
├── react@15.5.4
├── react-addons-pure-render-mixin@15.5.2
├── react-awesome-modal@2.0.1
├── react-dom@15.5.4
├── react-geosuggest@2.1.0
├── react-router@4.1.1
├── react-router-dom@4.1.1
└── simpl-schema@0.2.3
```

My installed meteor packages
```
aldeed:collection2-core  2.0.0  Core package for aldeed:collection2
autopublish              1.0.7  (For prototyping only) Publish the entire database to all clients
blaze-html-templates     1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
check                    1.2.5  Check whether a value matches a pattern
ecmascript               0.7.3  Compiler plugin that supports ES2015+ in all .js files
es5-shim                 4.6.15  Shims and polyfills to improve ECMAScript 5 support
insecure                 1.0.7  (For prototyping only) Allow all database writes from the client
meteor-base              1.0.4  Packages that every Meteor app needs
mobile-experience        1.0.4  Packages for a great mobile user experience
mongo                    1.1.16  Adaptor for using MongoDB and Minimongo over DDP
react-meteor-data        0.2.9  React mixin for reactively tracking Meteor data
reactive-var             1.0.11  Reactive variable
session                  1.1.7  Session variable
shell-server             0.2.3  Server-side component of the `meteor shell` command.
standard-minifier-css    1.3.4  Standard css minifier used with Meteor apps by default.
standard-minifier-js     2.0.0  Standard javascript minifiers used with Meteor apps by default.
std:accounts-ui          1.2.20  Accounts UI for React in Meteor 1.3+
tracker                  1.1.2  Dependency tracker to allow reactive callbacks
```

**Comment by FBosler** [comment]
Figured it out myself, had to run 
`npm i --save tracker-component`
