### ISSUE TITLE
Another newbie question

### ISSUE THREAD

**Issue by felixb101** [studiointeract/accounts-ui#34]
I keep getting "Signups forbidden", even with

 forbidClientAccountCreation: false

I did a meteor reset a few times...please advise

**Comment by felixb101** [comment]
Found it, required this on the server:

// Validate username, without a specific error message.
Accounts.validateNewUser(function (user) {
  return user.username !== "root";
});

**Comment by timbrandin** [comment]
Is that something you had in your app before? I haven't seen this before being required. 

Btw, how is the package working out for you so far?

**Comment by jaysig** [comment]
I'm having this issue as well. Any possible solutions, because that didn't work for me.

**Comment by sunlee-newyork** [comment]
@felixb101 thanks for the solution. It didn't work for me though - I'm getting this error:

```
W20160721-19:18:48.177(-4)? (STDERR) /Users/air/.meteor/packages/meteor-tool/.1.3.5_1.1qd5g0m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160721-19:18:48.178(-4)? (STDERR) 						throw(ex);
W20160721-19:18:48.179(-4)? (STDERR) 						      ^
W20160721-19:18:48.398(-4)? (STDERR) Error: Can't set `forbidClientAccountCreation` more than once
W20160721-19:18:48.399(-4)? (STDERR)     at packages/accounts-base/accounts_common.js:139:17
W20160721-19:18:48.400(-4)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
W20160721-19:18:48.400(-4)? (STDERR)     at AccountsServer.config (packages/accounts-base/accounts_common.js:136:7)
W20160721-19:18:48.400(-4)? (STDERR)     at AccountsServer.Ap.config (packages/accounts-base/accounts_server.js:1121:53)
W20160721-19:18:48.401(-4)? (STDERR)     at meteorInstall.imports.startup.server.js (imports/startup/server.js:4:10)
W20160721-19:18:48.401(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160721-19:18:48.402(-4)? (STDERR)     at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160721-19:18:48.402(-4)? (STDERR)     at Module.Mp.import (/Users/air/.meteor/packages/modules/.0.6.5.118suml++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20160721-19:18:48.402(-4)? (STDERR)     at meteorInstall.server.main.js (server/main.js:1:8)
W20160721-19:18:48.403(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
```

It looks like the `forbidClientAccountCreation` option isn't able to overwrite. Did you run into this issue?

**Comment by sunlee-newyork** [comment]
@felixb101 never mind! I had another accounts package `useraccounts:core` installed that probably had that option being set too. Fixed now. Can't believe I spent that long on this one haha.
